[tool:pytest]
testpaths = app/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --tb=short
    --disable-warnings
    --cov=.
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=80
markers =
    unit: Pruebas unitarias
    integration: Pruebas de integración
    slow: Pruebas lentas
    customer: Pruebas de clientes
    meal: Pruebas de combos
    order: Pruebas de pedidos
